# Session 1: Warmup

## Before starting
Please watch this short introduction to Jupyter Notebooks: https://www.youtube.com/watch?v=jZ952vChhuI

## Load Python libraries

In [3]:
import numpy as np
from numpy import random
import pandas as pd
import matplotlib.pyplot as plt

## 1. Introduction to numpy
Numerical Python (NumPy) is built on linear algebra. It is mainly used to perform mathematical calculations on vectors and matrices. 

In [4]:
#---------------------------------------------------
# Given the vector
a = np.array([2, 1, 4])
# with shape:
print(a.shape)
lenght = a.shape

# Ex.1.1
# Access to column value at position pos=2 using a[pos]
# Be aware that indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1, ...
print(a[2])

# Ex.1.2
# Access to the values from inititial position ini_pos=2 until the end of the vector final_pos = a.shape[-1] using a[initial_pos:final_pos]
# Note that the final raw or column of an array can be accesed by index -1

initPos = 2
final_pos = a.shape[-1]
for i in range(initPos - 1, final_pos):
    print(a[i])

# Check the data format of vector "a" by using type(a). Do the same for "a.shape". 
#For more information go to: https://www.w3schools.com/python/python_datatypes.asp


(3,)
4
1
4


In [5]:
#---------------------------------------------------
# Ex.1.3
# Given the matrix
X = np.array([[1, 2, 3], [8, 9, 10],[ 11, 12, 13]])
print(X)

# Access to all the elements at column 2 using X[:,column]

#First one is the numpy version, second is how default python would do
print(X[1,1])
print(X[1][1])
print(X[:, 1])


# numpy uses the ":" mark to access to all the elements of a column or a row 
# Access only to the diagonal using np.diag()

print(np.diag(X))

#this is the offset for to get diagonal  values
print(np.diag(X, -1))
print(np.diag(X, 1), "\n")
# Transpose the matrix using both np.transpose() and X.T

print(f"transpose with funcion: \n{np.transpose(X)}\n")
print(f"transpose with method: \n{X.T}\n")

[[ 1  2  3]
 [ 8  9 10]
 [11 12 13]]
9
9
[ 2  9 12]
[ 1  9 13]
[ 8 12]
[ 2 10] 

transpose with funcion: 
[[ 1  8 11]
 [ 2  9 12]
 [ 3 10 13]]

transpose with method: 
[[ 1  8 11]
 [ 2  9 12]
 [ 3 10 13]]



In [2]:
#--------------------------------------------------
# Ex.1.4
# Perform an element wise multiplication (*) between a and X
print(f"a: \n{a}\n")
print(f"a: \n{X}\n")
print(f"multiplied: \n{a*X}\n")
# Perform a dot wise multiplication between a and X using np.dot(vector1,vector2)
print(f"dot wise multiplication: \n{np.dot(a,X)}\n")

NameError: name 'a' is not defined

In [ ]:
#--------------------------------------------------
# Let us redefine vector "a" as a vector with 1 row and |a| columns
a = a.reshape((1,a.shape[-1]))
print(f"a = \n{a}\n")
# Ex.1.5
# Create a new matrix Y, where 'a' is added as the last row of matrix X
# Use np.concatenate((X,a), axis = 0) 

Y = np.concatenate((X,a), axis = 0)
print(f"Y: \n{Y}\n")
# Review the function of 'axis' in https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

# Ex.1.6
# Append 'a' as the last column of matrix X

print(f"Appened: \n{np.append(X, a)}\n")

## 2. Introduction to Pandas
This is a library for data manipulation and analysis using more powerful data structures than NumPy. 

In [ ]:
# Creating a Pandas DataFrame
column_names = ['Col1','Col2']
raw_names = ['Row1','Row2']
data = np.array([[1,2],[3,4]])
df = pd.DataFrame(data = data, index = raw_names, columns = column_names)
df

In [ ]:
# Ex.2.1
# Create an 10x4 (10 rows x 4 columns) pandas DataFrame in which the columns are named mean, std, max, and min.

column_names = ['mean','std','max', 'min']
data = random.randint(1000, size=(10, 4))
myDF = pd.DataFrame(data = data, columns = column_names)
myDF
# Populate each of the 12 cells in the DataFrame with a random integer between 0 and 1000
# Use the command np.random.randint for the random integer generation, check the description here https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html


In [ ]:
# Ex.2.2
# Access to all the values of the first row using df.loc[row]
print(myDF.loc[0])

# Access to all the values of the first column "mean" using df[column_name]
print(f"\n{myDF['mean']}\n")

# Access to the values in row 0 column 2 using df.iloc[row,column]
print(df.iloc[0,1])

## Introduction to Matplotlib

In [ ]:
# Ploting Pandas data
myDF['mean'].plot()
myDF['std'].plot()
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.title("Line Graph Example")
plt.legend()
plt.show()

In [11]:

names = ['x','f(x)']
exdata = np.array([[1,2,3,4,5,6],[16,9,4,1,4,9]])
df = pd.DataFrame(data = exdata, columns = names)
df

ValueError: Shape of passed values is (2, 6), indices imply (2, 2)